branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: GameLogic
    - DOXYFILE: ${TRAVIS_BUILD_DIR}/DOXYFILE
    - GH_REPO_REF: github.com/SoPra-Team-10/GameLogic.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

services:
  - docker

before_install:
  - docker build -t gamelogic .

script:
  - docker run gamelogic Tests/Tests --gtest_repeat=10 --gtest_shuffle --gtest_color=yes
  - docker run -e SONAR_TOKEN=${SONAR_TOKEN} -e TRAVIS_BRANCH=${TRAVIS_BRANCH} gamelogic bash -c cd /src && chmod +x run-sonarqube.sh && ./run-sonarqube.sh

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
  
notifications:
    slack: soprateam10:${TRAVIS_TOKEN}